### ISSUE TITLE
External markdown does not respect anchors

### ISSUE THREAD

**Issue by userbradley** [fire1ce/mkdocs-embed-external-markdown#11]
## Example

External markdown is as below

```
## Install
To enable the sensitive workflow add `sensitive: true` [to the Action](#sensitive)

# Sensitive

blah blah blah

```

Which renders fine on the page, but when you click on the link, it takes the users to the `raw.githubusercontent.com` page for that external markdown.

Screenshot of the rendered page

<img width="565" alt="image" src="https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/41597815/44b23af0-c299-4073-b9bc-5c613dc1f919">

ToC

<img width="245" alt="image" src="https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/41597815/7588cc92-6d6c-4261-a4d4-38cf2d730012">

Link when clicking on the `to the Action` link

![image](https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/41597815/680e6713-6dfc-4fe7-bb1a-6e92a29a6ee2)

**Comment by sdruskat** [comment]
#14 fixes the simple case described here, where the anchor is on the same page (`[Link text](#anchor)`).

Note that relative links to anchors on another page will still break (e.g., `[Link text](other-page.md#anchor)`). Happy to open another issue for this, or use this one further.

**Comment by userbradley** [comment]
Awesome sauce, thank you for looking at this <3
