### ISSUE TITLE
Cannot compatible with Mkdocs-Macros plugin

### ISSUE THREAD

**Issue by yanedie** [fire1ce/mkdocs-embed-external-markdown#12]
Mkdocs-Macros transforms the markdown pages into Jinja2 templates. So if I use two plugins at the same time, the command line will raise an error: jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'external_markdown'. Could you fix this problem? Because I use variables in many places, adding {% raw %} into respective places is inconvenient. 
A plugin called [mkdocs-include-markdown-plugin](https://github.com/mondeja/mkdocs-include-markdown-plugin) can customize the opening tag and closing tag, hope it can be helpful to you in fixing this issue! THX!

**Comment by fire1ce** [comment]
this is not my plugin problem. it's Jinja2 implimentation in MKDOCS
