### ISSUE TITLE
How do this work for local mkdocs installation? 

### ISSUE THREAD

**Issue by steele-ntwrk** [fire1ce/mkdocs-embed-external-markdown#13]
Hey, 

I am running a headless mkdocs installation on Ubuntu machine, when I go to create an external link I get the error below and nothing renders. 

![image](https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/80499933/6aafedc6-9298-437a-9e1a-5e802996d971)

This is my current configuration in my markdown file. I have tried to replace the specific IP with "localhost" but it still does not render. 

![image](https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/80499933/31396235-9eae-4111-9c13-0f7f449c9ec9)

Looking at your code, does this only work if its hosted on github pages? 

Cheers,
Steele

**Comment by fire1ce** [comment]
There should be no issue running it with any types of IPs as long the address is accessible from the build env.
Also read the docs again, you have a mistake with your example:
https://github.com/fire1ce/mkdocs-embed-external-markdown#full-markdown-content
"#" is H1, you should not provide a Title to be parsed. 

not an issue.

**Comment by steele-ntwrk** [comment]
Hi 

I modified it to H2 and tried numerous tests such as:
![image](https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/80499933/54910a84-7cac-49e3-8d48-deace888391a)

- Changing the reference IP and mkdocs IP to 127.0.0.1 and localhost
- Confirmed I could curl to the link on all 3 ip addresses from the build box
![image](https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/80499933/6b9ecca5-b1e9-4bdf-9f9c-4b46e9af23c6)

I managed to get pass connection refused or 404 error and instead the debug got stuck on the md file where the embedding lives. 
![image](https://github.com/fire1ce/mkdocs-embed-external-markdown/assets/80499933/290eab5b-5af0-4ccc-8177-42f99021fb55)

It's probably an issue with the buildbox and hosting server are the same.
