### ISSUE TITLE
Do local files support?

### ISSUE THREAD

**Issue by steam3d** [fire1ce/mkdocs-embed-external-markdown#16]
I want to include files that already stored in mkdocs. Something like this:

```
docs/
----- note.md
----- external.md
```

```
# External.md file content:

{{ external_markdown('note.md', '') }}

```

This line check URL, but it is local file: 
https://github.com/fire1ce/mkdocs-embed-external-markdown/blob/60407790bc6b578dafae23d2260dacc16ecd3f36/external_markdown/plugin.py#L119

It turns out that local files are not supported?

**Comment by fire1ce** [comment]
No. The name of the plugin is External.
Use mkdocs for local files.
