### ISSUE TITLE
How to get this working with private repositories

### ISSUE THREAD

**Issue by sd0408** [fire1ce/mkdocs-embed-external-markdown#3]
Private repos require a personal access token to see their raw files. I would like to use this plugin within our organization but I we have private repos. I can make a fork, and work on the code but want to know if this feature is one that you would want to support in upstream.

I'm thinking of defining an environment variable that can be used to grab the personal access token and then appending that token to the url if that environment variable is set.

**Comment by fire1ce** [comment]
@sd0408 Hey, right now i don't have intentions to add private repos support. If you can make it work PR would be welcomed. Take in consideration using git repo secrets so it can be implemented in a proper ci.
