### ISSUE TITLE
Not all sections are discovered.

### ISSUE THREAD

**Issue by mercenaruss** [fire1ce/mkdocs-embed-external-markdown#8]
Hi,
have next problem:
I use next example to include just a section of this .md
```markdown
{{ external_markdown('https://raw.githubusercontent.com/Koenkk/zigbee2mqtt.io/master/docs/guide/faq/README.md', '## What does and does not require repairing of all devices?') }}
```

But i get next error:
```markdown
Error! Section: "## What does and does not require repairing of all devices?" not found in markdown https://raw.githubusercontent.com/Koenkk/zigbee2mqtt.io/master/docs/guide/faq/README.md
```
What can be the issue?he identify just some of the section of the .md file.
Thanks

**Comment by fire1ce** [comment]
probably something with regex. if ill have time ill try dbug it this week. 
thanks for the info. it will help.

**Comment by fire1ce** [comment]
@mercenaruss 
Haven’t forgotten about the issue. 
Got some work done. Seems like i’ve solved the issues and also added better functionality for the plugin on the way. need to do some more testing before the release.

**Comment by fire1ce** [comment]
Version 3.0.0 (2023-06-20) is out. It will fix this issue.
